name: Docker Image CI and publish

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#  release:
#    types: [published]

jobs:

  push_to_registry:
    name: Build and push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.ASDC_PACKAGES }}
          registry: ghcr.io
          repository: auscalabledronecloud/nvidia-driver-container
          tag_with_ref: true
          file: Dockerfile.fedatomic 
