name: Docker Image CI and publish

on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile.fedatomic'
      - 'scripts/**'
#  pull_request:
#  release:
#    types: [published]

jobs:

  push_to_registry:
    name: Build and push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ASDC_PACKAGES }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/auscalabledronecloud/nvidia-driver-container:fedora-coreos-5.7.16-200.fc32.x86_64-460.32.03
          file: ./Dockerfile.fedatomic
          push: true

